# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 700ce50dd00cb0d862d1fd6ab772189d6709f296315fb988c7eabf00d14a50726072d5bf653d4da098e8083127cd93bae5a51c36a029c16d936641c3d8ff4bb5

test:
  secret_key_base: 5296444cf44520ea4a07f82f55a14073b20dd8008c47765cf7110ab55c1fd14ef72cd4c1adb870dbcb376fe7f027a1961a973af15f853896d546b06e6ebf252e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
